version: '3.8'
services:
  webapp:
    build: ./webapp
    ports:
      - '3000:3000'
    volumes:
      - './webapp:/usr/src/app'
      - '/usr/src/app/node_modules'
    networks:
      - app
    depends_on:
      - laravel
  laravel:
    build: ./backend
    ports:
      - '3001:8000'
    volumes:
      - './backend:/usr/src/app'
    networks:
      - app
networks:
  app:

